### ISSUE TITLE
LogicException: Cannot set session ID after the session has started.

### ISSUE THREAD

**Issue by rkempter** [psliwa/PdfBundle#56]
Using your bundle, everything works fine in dev. Unfortunately, when running my functional tests, using with MockFileSessionStorage for the session & authentication, I get the exception "Cannot set session ID after the session has started" from setId in MockArraySessionStorage (MockFileSessionStorage extends MockArraySessionStorage). Do you have an idea where the problem could be?

Thanks!

**Comment by gido** [comment]
I digged a bit into the issue and it looks like the root of this issue is coming from `Ps\PdfBundle\EventListener\PdfListener`.

I think the main issue is that this service are build on every request (listen for `kernel.request`) and generate the creation of all it's dependencies too early (or one of it's dependencies get things messy, more probably the template engine).

I "fixed" my issue by splitting the listener into two services: a light service for the setting the `pdf` format on the request and the existing one. I will create a PR to illustrate this.

If someone have a better overview of what is going bad here, I will be happy to learn :-)
